name: meehancoaching
favicon: null
layout_spectrum: 0.76405
typography_spectrum: 0.41382
title: Meehan Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#1d9b91'
    - '#007f93'
    - '#008080'
    - '#15958a'
    - '#005555'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
