name: meehancoaching
favicon: null
layout_spectrum: 1
typography_spectrum: 0.41382
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#B8B42D'
    - '#697A21'
    - '#FFFCE8'
    - '#3E363F'
    - '#DD403A'
  brandStrength: 0.5
  lightness: 0.12110051163472235
  saturation: 0.9651111492421478
  rhythmicContrast: 0.3636052936781198
purpose: []
