name: meehancoaching
favicon: null
layout_spectrum: 0.48672
typography_spectrum: 0.41382
title: Meehan Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#008db0'
    - '#818286'
    - '#a6d9e4'
    - '#4fafc8'
  brandStrength: 1
  lightness: 0.6875
  saturation: 0.375
  rhythmicContrast: 0.5
purpose: []
