name: meehancoaching
favicon: null
layout_spectrum: 0.49282
typography_spectrum: 0.41382
title: Meehan Coaching
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#000000'
    - '#ffffff'
    - '#5c5c5e'
    - '#222d0f'
    - '#a7846c'
  brandStrength: 0.1875
  lightness: 0.375
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
